### ISSUE TITLE
Problem connecting form zimlet to odoo

### ISSUE THREAD

**Issue by rovincent** [vnc-biz/openerp-zimbra-connector#3]
Hi Guys,

I have installed seemingly (no errors) both the zimlet 1.2.5.10 and the vnc_zimbra_connector master-8 form this repo.

However i constantly get "Host could not be reached" from the zimlet configuration when getting the db?

Form both the web client host and the zimbra server i can ping and browse to the odoo server ?

any hints ?

Robin

**Comment by rovincent** [comment]
Apologies I found the issue.

I had set the openerp-server.conf > list_db = False

for security reasons, once this was set to true i was able to connect.

Robin

**Comment by dhaval-vnc** [comment]
Glad that the problem solved. Sorry for late reply.
